# Generated by Django 4.2.30 on 2026-06-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courseaccess',
            new_name='payments_co_user_id_10239a_idx',
            old_name='payments_ca_user_course_idx',
        ),
        migrations.RenameIndex(
            model_name='courseaccess',
            new_name='payments_co_user_id_24b87a_idx',
            old_name='payments_ca_user_idx',
        ),
    ]
