import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'EN' | 'AM' | 'OM';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'hero.badge': 'Updated for 2018',
    'hero.title.top': 'Get the GPA',
    'hero.title.highlight': 'Deserve',
    'hero.title.bottom': 'You',
    'hero.subtitle': 'Study Smarter, Practice Better, and Thrive. From Grade 12 National Exam to your University Freshman courses, we give you the exact tools you need to succeed.',
    'hero.cta.entrance': 'Entrance Prep',
    'hero.cta.freshman': 'Freshman Portal',
    'why.title': 'Why Tilla?',
    'why.optimized': 'Education, optimized.',
    'why.strategy': 'We don\'t want you wasting time on 1,000 pages of things that never appear on the exam. Our curriculum is built to give you only the most important information. We focus on what matters to launch you to the sky.',
    'pricing.title': 'Small Price for a Big Future.',
    'pricing.subtitle': 'Your future is worth it. Stop worrying about difficult exams. For a small price, we give you the exact path to an \'A\'. Choose your path below and unlock your portal immediately.',
    'universities.trusted': 'Trusted by students from',
    'services.title': 'Pick your path.',
    'services.subtitle': 'We have two ways to help you. One for Grade 12 students to pass the national exam (EHEECE), and one for Freshman students to get a high GPA and join their dream department. Everything you need to succeed is right here in one place.',
    'services.entrance.title': 'Entrance Prep',
    'services.entrance.desc': 'The Exam is coming. Don\'t just study the textbook learn how to answer the questions that actually appear. Your future depends on this one exam. Use our smart practice questions to find your weak spots and fix them before the big day.',
    'services.freshman.title': 'Freshman Portal',
    'services.freshman.desc': 'Your first year at university is the most important. One low grade can lose you the department you love. We provide notes, practice questions and explanation videos for all common courses so you can keep a high GPA. Stay on track for your dream with Tilla.',
    'services.more': 'More Info',
    'services.register': 'Register Now',
    'pricing.entrance.header': 'Entrance Prep',
    'pricing.freshman.header': 'Freshman Portal',
    'pricing.viewMore': 'View More',
    'pricing.close': 'Close Details',
    'pricing.overview': 'Plan Overview',
    'pricing.included': 'What\'s Included',
    'pricing.proceed': 'Proceed to Payment',
    'pricing.semester.title': 'Select Your Semester',
    'pricing.semester.subtitle': 'Which semester are you currently in? We\'ll tailor your course list accordingly.',
    'pricing.courses.title': 'Select Your Courses',
    'pricing.courses.subtitle': 'Select the courses your university is giving this semester (Max 8).',
    'pricing.join': 'Join Now',
    'pricing.premium': 'Go Premium',
    'pricing.start': 'Start Learning',
    'pricing.best': 'Best Value',
    'why.feature.1.title': 'Focus on What Matters',
    'why.feature.1.desc': 'We find the 20% of the course that always appears in 80% of the exam questions. We show you exactly where the marks are hidden.',
    'why.feature.2.title': 'No Useless Content',
    'why.feature.2.desc': 'Our notes are lean and direct, designed for the busy Ethiopian student. You get high-impact content that helps you understand deep logic in just a few minutes.',
    'why.feature.3.title': 'Expert Curation',
    'why.feature.3.desc': 'Every course and note is vetted by top-performing students from leading Ethiopian universities.',
    'why.feature.4.title': 'Interactive Learning',
    'why.feature.4.desc': 'Engage with video lectures, interactive quizzes, mid and final exams and real-time feedback to master complex concepts faster.',
    'why.feature.5.title': 'Global Community',
    'why.feature.5.desc': 'Connect with thousands of freshman students across the country to share resources and solve problems together.',
    'why.feature.6.title': 'Verified Content',
    'why.feature.6.desc': 'Rest easy knowing all study materials are accurate, up-to-date, and aligned with the national curriculum.',
    'why.feature.7.title': 'Senior Student Secrets',
    'why.feature.7.desc': 'We are like a community. We connect you with seniors who have already finished your courses. They tell you the truth about the exams and the instructors.',
    'about.title.part1': 'About',
    'about.title.highlight': 'Tilla Academy',
    'about.description': 'Tilla Academy is an educational platform built for ambitious Ethiopian students. We know that the road to success in our country can be very difficult and stressful. Our goal is to make your journey smoother and clearer.',
    'about.focus.title': 'Our Core Focus',
    'about.focus.desc': 'We focus on the two most important milestones in your academic life: Grade 12 and Freshman Year. These years define your future, and we are here to ensure you win.',
    'about.focus.tag1': 'Grade 12 Prep',
    'about.focus.tag2': 'Freshman Success',
    'about.goal.title': 'Our Goal',
    'about.goal.desc': 'At Tilla Academy, we want to turn your academic pressure into academic power.',
    'about.entrance.title': 'Grade 12 Entrance Exam Prep',
    'about.entrance.desc': 'Taking a national exam that covers four years of books is overwhelming. We break down the massive curriculum into simple, easy-to-study parts.',
    'about.freshman.title': 'Freshman Success Portal',
    'about.freshman.desc': 'Starting university is a big change. We provide the right roadmaps and resources for your first-year courses to help you reach your dreams.',
    'about.final.message': 'Whether you are studying for your entrance exam or navigating your first year of campus life, we are here to guide you.',
    'about.final.cta': 'Start Your Journey Today',
    'faq.title': 'Common Questions',
    'faq.help': 'Quick Help',
    'faq.help.desc': 'Need immediate assistance? Our support team is active on multiple platforms.',
    'faq.seeMore': 'See More Questions',
    'faq.seeLess': 'See Less',
    'courses.explore.title': 'Explore Courses',
    'courses.explore.desc': 'Explore our comprehensive list of subjects. We provide notes, practice questions and explanation videos.',
    'courses.entrance.title': 'Entrance Prep Courses',
    'courses.entrance.desc': 'Prepare for your university entrance exams with our comprehensive subject-specific courses.',
    'courses.search.placeholder': 'Search subjects...',
    'courses.natural': 'Natural Science',
    'courses.social': 'Social Science',
    'courses.noResults': 'No courses found matching',
    'footer.desc': 'More than just a platform, we are a community for success. We combine expert notes with senior student advice to empower every Ethiopian student.',
    'footer.platform': 'Platform',
    'footer.legal': 'Legal',
    'footer.dataSaver': 'Data Saver',
    'footer.enabled': 'Enabled',
    'footer.disabled': 'Disabled',
    'freshman.portal.title': 'Freshman Portal',
    'freshman.portal.desc': 'The Freshman Portal is your essential companion for navigating the first year of university. We help you stay on track with your GPA and make informed decisions about your future department.',
    'freshman.whatYouGet.title': 'What You Get',
    'freshman.whatYouGet.desc': 'The Freshman Portal provides you with the data and tools needed to excel in your first year. You\'ll be able to track your academic progress accurately and understand the requirements for your desired department, reducing the stress of university life.',
    'freshman.included.title': 'Included Services',
    'freshman.included.desc': 'Get familiar with the Tilla Language. We created these special names for the tools you will use.',
    'freshman.snapnotes.title': '1. Snap-Notes (Our PDF short notes)',
    'freshman.snapnotes.desc': 'We know you don\'t have time to read hundreds of pages. Snap-Notes are the best short notes for every chapter. We take long, confusing books and "snap" them into simple points. It is the fastest way to get the main idea without getting tired.',
    'freshman.conceptcrush.title': '2. Concept-Crush (Our videos)',
    'freshman.conceptcrush.desc': 'If a chapter feels too hard, Concept-Crush will fix it. These are high-quality videos on our website and private Telegram channel. We "crush" difficult topics until they are easy to understand. It’s like having a private tutor in your pocket.',
    'freshman.examcracker.title': '3. Exam-Cracker (Our chapter practice question bank)',
    'freshman.examcracker.desc': 'Don\'t be afraid of the exam. Exam-Cracker gives you thousands of practice questions from old and new exams. We show you the tricks instructors use to confuse you, so you can answer correctly every time.',
    'freshman.snapquiz.title': '4. Snap-Quiz (Our quick lesson tests)',
    'freshman.snapquiz.desc': 'Test yourself quickly. Snap-Quizzes are short, 5-minute tests you can take on your phone or computer. They help you remember what you just studied so the information stays in your brain for a long time.',
    'freshman.mockexams.title': '5. Custom Mid & Final Exams (Our mock exams)',
    'freshman.mockexams.desc': 'Before your real exam, take our custom Mock Exams. They are designed to look exactly like the real university tests. If you can pass our mock exam, you can pass the real one easily.',
    'freshman.brightslides.title': '6. Bright-Slides (Our visual review slides)',
    'freshman.brightslides.desc': 'Visual learning is better. Bright-Slides are beautiful, colorful slides that summarize each chapter. They are perfect for a last-minute review before you enter the exam hall.',
    'freshman.explore.title': 'Explore Courses',
    'freshman.explore.desc': 'Explore our comprehensive list of freshman subjects. We provide notes, practice questions and explanation videos for all common courses below.',
    'freshman.subscription.note': 'All services based on your subscription.',
  },
  AM: {
    'hero.badge': 'ለ 2018 የታደሰ',
    'hero.title.top': 'የሚገባዎትን',
    'hero.title.highlight': 'GPA',
    'hero.title.bottom': 'ያግኙ',
    'hero.subtitle': 'ብልህ በሆነ መንገድ ያጥኑ፣ የተሻለ ልምምድ ያድርጉ እና ይሳኩ። ከጥሩ 12 የብሔራዊ ፈተና እስከ ዩኒቨርሲቲ የፍሬሽማን ኮርሶች ድረስ ለስኬትዎ የሚያስፈልጉዎትን ትክክለኛ መሣሪያዎች እንሰጥዎታለን።',
    'hero.cta.entrance': 'የመግቢያ ፈተና',
    'hero.cta.freshman': 'የፍሬሽማን ፖርታል',
    'why.title': 'ለምን ቲላ?',
    'why.optimized': 'ትምህርት፣ በብቃት።',
    'why.strategy': 'ፈተና ላይ የማይመጡ 1,000 ገጾችን በማንበብ ጊዜዎን እንዲያባክኑ አንፈልግም። የእኛ ስርዓት በጣም አስፈላጊ የሆኑ መረጃዎችን ብቻ እንዲያገኙ ተደርጎ የተገነባ ነው። ግባችን እርስዎ ውጤታማ እንዲሆኑ ማድረግ ነው።',
    'pricing.title': 'ለትልቅ መጪ ጊዜ ትንሽ ክፍያ።',
    'pricing.subtitle': 'የእርስዎ የወደፊት ጊዜ ዋጋ አለው። ስለ አስቸጋሪ ፈተናዎች መጨነቅ ያቁሙ። በትንሽ ክፍያ ለ "A" ውጤት ትክክለኛውን መንገድ እናሳይዎታለን።',
    'universities.trusted': 'በተማሪዎች የታመነ ከ',
    'services.title': 'እንዴት መማር እንደሚፈልጉ ይምረጡ።',
    'services.subtitle': 'እኛ እርስዎን ለመርዳት ሁለት መንገዶች አሉን። አንደኛው ለ 12 ኛ ክፍል ተማሪዎች የብሔራዊ ፈተናን (EHEECE) እንዲያልፉ የሚያግዝ ሲሆን ሁለተኛው ደግሞ የፍሬሽማን ተማሪዎች ከፍተኛ GPA አግኝተው የሚወዱትን ዲፓርትመንት እንዲቀላቀሉ የሚረዳ ነው።',
    'services.entrance.title': 'የመግቢያ ፈተና ዝግጅት',
    'services.entrance.desc': 'ፈተናው እየደረሰ ነው። የመማሪያ መጽሐፉን ብቻ አያጥኑ - ትክክለኛውን የፈተና ጥያቄዎች እንዴት መመለስ እንደሚችሉ ይማሩ። የወደፊት ህይወትዎ በዚህ ፈተና ላይ የተመሰረተ ነው።',
    'services.freshman.title': 'የፍሬሽማን ፖርታል',
    'services.freshman.desc': 'በዩኒቨርሲቲ የመጀመሪያ ዓመትዎ በጣም አስፈላጊው ነው። አንድ ዝቅተኛ ውጤት የሚወዱትን ዲፓርትመንት ሊያሳጣዎት ይችላል። ከፍተኛ GPA እንዲኖርዎት ማስታወሻዎችን እና ጥያቄዎችን እናቀርባለን።',
    'services.more': 'ተጨማሪ መረጃ',
    'services.register': 'አሁን ይመዝገቡ',
    'pricing.entrance.header': 'የመግቢያ ፈተና',
    'pricing.freshman.header': 'የፍሬሽማን ፖርታል',
    'pricing.viewMore': 'ተጨማሪ ይመልከቱ',
    'pricing.close': 'ዝርዝሮችን ዝጋ',
    'pricing.overview': 'የዕቅድ አጠቃላይ እይታ',
    'pricing.included': 'ምን ተካቷል?',
    'pricing.proceed': 'ወደ ክፍያ ይቀጥሉ',
    'pricing.semester.title': 'ሴሜስተርዎን ይምረጡ',
    'pricing.semester.subtitle': 'አሁን በየትኛው ሴሜስተር ላይ ነዎት? የኮርስ ዝርዝርዎን በዛ መሠረት እናስተካክላለን።',
    'pricing.courses.title': 'ኮርሶችዎን ይምረጡ',
    'pricing.courses.subtitle': 'በዚህ ሴሜስተር ዩኒቨርሲቲዎ የሚሰጣቸውን ኮርሶች ይምረጡ (ከፍተኛ 8)።',
    'pricing.join': 'አሁን ይቀላቀሉ',
    'pricing.premium': 'ፕሪሚየም ይሁኑ',
    'pricing.start': 'መማር ይጀምሩ',
    'pricing.best': 'ምርጥ ምርጫ',
    'why.feature.1.title': 'በሚጠቅሙ ነገሮች ላይ ትኩረት ማድረግ',
    'why.feature.1.desc': 'በፈተናዎች ላይ ሁልጊዜ የሚመጡ ዋና ዋና ነጥቦችን እንለያለን። ውጤት የሚገኝባቸውን ቦታዎች እናሳይዎታለን።',
    'why.feature.2.title': 'አላስፈላጊ ይዘት የለም',
    'why.feature.2.desc': 'ማስታወሻዎቻችን አጭር እና ቀጥታ ናቸው። በትንሽ ደቂቃዎች ውስጥ ጥልቅ አመክንዮ እንዲረዱ ያደርጉዎታል።',
    'why.feature.3.title': 'በባለሙያ የተዘጋጀ',
    'why.feature.3.desc': 'እያንዳንዱ ኮርስ እና ማስታወሻ በታዋቂ የኢትዮጵያ ዩኒቨርሲቲዎች ከፍተኛ ውጤት ባመጡ ተማሪዎች የተረጋገጠ ነው።',
    'why.feature.4.title': 'በይነተገናኝ ትምህርት',
    'why.feature.4.desc': 'በቪዲዮ ትምህርቶች፣ ፈተናዎች እና የእውነተኛ ጊዜ ግብረመልስ አማካኝነት አስቸጋሪ ፅንሰ ሀሳቦችን በቶሎ ይገነዘባሉ።',
    'why.feature.5.title': 'አለምአቀፍ ማህበረሰብ',
    'why.feature.5.desc': 'በሀገር አቀፍ ደረጃ ከሚገኙ በሺዎች ከሚቆጠሩ የፍሬሽማን ተማሪዎች ጋር ይገናኙ እና እውቀት ይለዋወጡ።',
    'why.feature.6.title': 'የተረጋገጠ ይዘት',
    'why.feature.6.desc': 'ሁሉም የጥናት ቁሳቁሶች ትክክለኛ፣ ወቅታዊ እና ከሀገር አቀፍ ስርዓተ ትምህርት ጋር የተጣጣሙ ናቸው።',
    'why.feature.7.title': 'የቀድሞ ተማሪዎች ምስጢር',
    'why.feature.7.desc': 'ኮርሶቹን ከጨረሱ ተማሪዎች ጋር እናገናኝዎታለን። ስለ ፈተናዎች እና ስለ መምህራኑ እውነቱን ይነግሩዎታል።',
    'about.title.part1': 'ስለ',
    'about.title.highlight': 'ቲላ አካዳሚ',
    'about.description': 'ቲላ አካዳሚ ለታላሚ የኢትዮጵያ ተማሪዎች የተገነባ የትምህርት መድረክ ነው። በአገራችን የስኬት መንገድ በጣም አስቸጋሪ ሊሆን እንደሚችል እናውቃለን። ግባችን ጉዞዎን ቀላል እና ግልጽ ማድረግ ነው።',
    'about.focus.title': 'ዋና ትኩረታችን',
    'about.focus.desc': 'በትምህርት ሕይወትዎ ውስጥ በሁለቱ በጣም አስፈላጊ ደረጃዎች ላይ እናተኩራለን፡ 12ኛ ክፍል እና የፍሬሽማን ዓመት። እነዚህ ዓመታት የወደፊት ሕይወትዎን ይወስናሉ፣ እና እርስዎ እንዲያሸንፉ ለማድረግ እዚህ ነን።',
    'about.focus.tag1': 'የ12ኛ ክፍል ዝግጅት',
    'about.focus.tag2': 'የፍሬሽማን ስኬት',
    'about.goal.title': 'ግባችን',
    'about.goal.desc': 'በቲላ አካዳሚ፣ የትምህርት ጫናዎን ወደ ትምህርት ኃይል መለወጥ እንፈልጋለን።',
    'about.entrance.title': 'የ12ኛ ክፍል መግቢያ ፈተና ዝግጅት',
    'about.entrance.desc': 'የአራት ዓመት መጻሕፍትን የሚሸፍን ብሔራዊ ፈተና መውሰድ በጣም ከባድ ነው። ሰፊውን ሥርዓተ ትምህርት ወደ ቀላል እና ለማጥናት ምቹ ክፍሎች እንከፋፍለዋለን።',
    'about.freshman.title': 'የፍሬሽማን ስኬት ፖርታል',
    'about.freshman.desc': 'ዩኒቨርሲቲ መጀመር ትልቅ ለውጥ ነው። ሕልሞችዎ ላይ እንዲደርሱ ለማገዝ ለመጀመሪያው ዓመት ኮርሶች ትክክለኛውን የጥናት መንገድ እና ግብዓቶችን እናቀርባለን።',
    'about.final.message': 'ለመግቢያ ፈተናዎ እያጠኑም ይሁን የመጀመሪያውን የካምፓስ ሕይወትዎን እየመሩ፣ እርስዎን ለመምራት እዚህ ነን።',
    'about.final.cta': 'ጉዞዎን ዛሬ ይጀምሩ',
    'faq.title': 'የተለመዱ ጥያቄዎች',
    'faq.help': 'ፈጣን እርዳታ',
    'faq.help.desc': 'አስቸኳይ እርዳታ ይፈልጋሉ? የእኛ የድጋፍ ቡድን በተለያዩ መድረኮች ላይ ንቁ ነው።',
    'faq.seeMore': 'ተጨማሪ ጥያቄዎችን ይመልከቱ',
    'faq.seeLess': 'ያነሰ ይመልከቱ',
    'courses.explore.title': 'ኮርሶችን ያስሱ',
    'courses.explore.desc': 'የኮርሶቻችንን ሰፊ ዝርዝር ያስሱ። ማስታወሻዎችን፣ የልምምድ ጥያቄዎችን እና የቪዲዮ ማብራሪያዎችን እናቀርባለን።',
    'courses.entrance.title': 'የመግቢያ ፈተና ዝግጅት ኮርሶች',
    'courses.entrance.desc': 'ለዩኒቨርሲቲ መግቢያ ፈተናዎችዎ አጠቃላይ በሆኑ የትምህርት ዓይነት ኮርሶቻችን ይዘጋጁ።',
    'courses.search.placeholder': 'ትምህርቶችን ይፈልጉ...',
    'courses.natural': 'የተፈጥሮ ሳይንስ',
    'courses.social': 'የማኅበራዊ ሳይንስ',
    'courses.noResults': 'ከዚህ ጋር የሚዛመድ ኮርስ አልተገኘም',
    'footer.desc': 'ከመድረክ በላይ፣ እኛ ለስኬት የተቋቋምን ማህበረሰብ ነን። እያንዳንዱን ኢትዮጵያዊ ተማሪ ለማብቃት የባለሙያ ማስታወሻዎችን ከቀድሞ ተማሪዎች ምክር ጋር እናጣምራለን።',
    'footer.platform': 'መድረክ',
    'footer.legal': 'ሕጋዊ',
    'footer.dataSaver': 'ዳታ ቆጣቢ',
    'footer.enabled': 'በርቷል',
    'footer.disabled': 'ጠፍቷል',
  },
  OM: {
    'hero.badge': '2018\'f haara\'ome',
    'hero.title.top': 'GPA isiniif',
    'hero.title.highlight': 'Malu',
    'hero.title.bottom': 'Argadhaa',
    'hero.subtitle': 'Akka qaranitti baradhu, akka gaariitti shaakali, mo\'adhu. Qormaata biyyaalessaa kutaa 12ffaa irraa kaasee hanga koorsiiwwan Freshman yunivarsiitii keessaniitti, meeshaalee milkaa\'ina keessaniif isin barbaachisan isiniif kennina.',
    'hero.cta.entrance': 'Qophii Seensaa',
    'hero.cta.freshman': 'Freshman Portal',
    'why.title': 'Maaliif Tiillaa?',
    'why.optimized': 'Barnoota, mijaawaa.',
    'why.strategy': 'Fuula 1,000 qofaa gubuurra, barumsa qormaata irratti dhufan qofa akka barattan isin gargaarra. Kaayyoon keenya milkaa\'ina keessaani.',
    'pricing.title': 'Borii Keessaniif Kaffaltii Xiqqaa.',
    'pricing.subtitle': 'Fuuldurri keessan gatii guddaa qaba. Qormaata qoruun hin dhiphatinaa. Kaffaltii xiqqaadhaan karaa milkaa\'inaa fidu isiniif dhiyeessina.',
    'universities.trusted': 'Barattootaan kan amaname kan',
    'services.title': 'Akkaataa Barachuu Barbaaddan Filadhaa.',
    'services.subtitle': 'Isin gargaaruuf karaa lama qabna. Inni tokko barattoota kutaa 12ffaa qormaata biyyaalessaa (EHEECE) akka darban gargaaruuf, inni kaan immoo barattoota Freshman GPA olaanaa galmeessisanii muummee barbaadan akka galan gargaaruuf.',
    'services.entrance.title': 'Qophii Seensaa',
    'services.entrance.desc': 'Qormaanni dhiyaataa jira. Kitaaba qofa hin qara\'inaa - akkaataa gaaffiiwwan qabatamaan dhufan itti deebiftan baradhaa.',
    'services.freshman.title': 'Freshman Portal',
    'services.freshman.desc': 'Waggaan jalqabaa yunivarsiitii keessatti baay\'ee barbaachisaadha. Qabxiin gadi bu\'aan tokko muummee jaallattan isin dhabsiisuu danda\'a.',
    'services.more': 'Odeeffannoo Dabalataa',
    'services.register': 'Amma Galmaa\'aa',
    'pricing.entrance.header': 'Qophii Seensaa',
    'pricing.freshman.header': 'Freshman Portal',
    'pricing.viewMore': 'Dabalataan Ilaali',
    'pricing.close': 'Cufi',
    'pricing.overview': 'Maxxansa Karooraa',
    'pricing.included': 'Maaltu Itti Dabale?',
    'pricing.proceed': 'Gara Kaffaltiitti Darbi',
    'pricing.semester.title': 'Imala Keessan Filadhaa',
    'pricing.semester.subtitle': 'Amma semisteera isa kam irra jirtu? Akka kanaan tarree koorsii keessanii qopheessina.',
    'pricing.courses.title': 'Koorsii Keessan Filadhaa',
    'pricing.courses.subtitle': 'Koorsiiwwan semisteera kana yunivarsiitiin keessan kennu filadhaa (Max 8).',
    'pricing.join': 'Amma Miseensa Ta\'i',
    'pricing.premium': 'Premiyeemii Ta\'i',
    'pricing.start': 'Barachuu Jalqabi',
    'pricing.best': 'Baay\'ee Filatamaa',
    'why.feature.1.title': 'Waan Barbaachisaa Ta\'e Irratti Xiyyeeffachuu',
    'why.feature.1.desc': 'Qabxiiwwan qormaata irratti yeroo hunda dhufan adda baafnee isiniif dhiyeessina.',
    'why.feature.2.title': 'Qabiyyee Faይidaa Hin Qabne Hin Qabu',
    'why.feature.2.desc': 'Yaadannoon keenya gabaabaa fi ifaadha. Daqiiqaa muraasa keessatti akka hubattun isin gargaara.',
    'why.feature.3.title': 'Ogeessaan Kan Qophaa\'e',
    'why.feature.3.desc': 'Barumsi hundi barattoota yunivarsiitii qabxii olaanaa qabaniin kan mirkanaa\'edha.',
    'why.feature.4.title': 'Barnoota Interaktiivii',
    'why.feature.4.desc': 'Viidiyoo, qormaata shaakalaa fi yaada battalaa gargaaramuun dandeettii keessan cimsadhaa.',
    'why.feature.5.title': 'Hawaasa Addunyaa',
    'why.feature.5.desc': 'Barattoota Freshman biyya hunda keessa jiran waliin wal qunnamaa, beekumsa wal hiraa.',
    'why.feature.6.title': 'Qabiyyee Mirkanaa\'e',
    'why.feature.6.desc': 'Meesshaaleen barumsaa hundi sirrii fi sirna barnootaa biyyaalessaa waliin kan walsimanidha.',
    'why.feature.7.title': 'Iccitii Barattoota Angafa',
    'why.feature.7.desc': 'Barattoota koorsii kana xumuran waliin isin wal qunnamsiisna. Dhugaa qormaata isiniif himu.',
    'about.title.part1': 'Waa\'ee',
    'about.title.highlight': 'Tilla Academy',
    'about.description': 'Akkaadaamiin Tiillaa maddee barnootaa barattoota Itoophiyaa qaxalee ta\'aniif qophaa\'eedha. Karaan milkaa\'ina biyya keenya keessatti rakkisaa ta\'uu danda\'u ni beekna. Kaayyoon keenya adeemsa keessan salphaa fi ifa gochuudha.',
    'about.focus.title': 'Xiyyeeffannoo Keenya',
    'about.focus.desc': 'Sadarkaa barnootaa keessan keessatti yeroo lamaan baay\'ee barbaachisoo ta\'an irratti xiyyeeffanna: Kutaa 12ffaa fi Waggaa Freshman. Waggoonni kun fuuldura keessan ni murteessu.',
    'about.focus.tag1': 'Qophii Kutaa 12ffaa',
    'about.focus.tag2': 'Milkaa\'ina Freshman',
    'about.goal.title': 'Kaayyoo Keenya',
    'about.goal.desc': 'Akkaadaamii Tiillaa keessatti, dhiphina barnootaa keessan gara humna barnootaatti jijjiiruu barbaanna.',
    'about.entrance.title': 'Qophii Qormaata Seensaa Kutaa 12ffaa',
    'about.entrance.desc': 'Qormaata biyyaalessaa kitaabota waggaa afurii covers godhu fudhachuun baay\'ee ulfaataadha. Sirna barnootaa ballaa kana gara kutaalee salphaatti addaan baafna.',
    'about.freshman.title': 'Freshman Success Portal',
    'about.freshman.desc': 'Yunivarsiitii jalqabuun jijjiirama guddaadha. Galma keessan bira akka geessaniif koorsiiwwan waggaa tokkooffaatiif qajeelfama sirrii fi meeshaalee barbaachisoo isiniif kennina.',
    'about.final.message': 'Qormaata seensaatiif qara\'us ta\'ee jireenya kaampaasii waggaa jalqabaa keessan keessa darbaa jiraattus, builds isin qajeelfuuf as jra.',
    'about.final.cta': 'Adeemsa Keessan Har\'a Jalqabaa',
    'faq.title': 'Gaaffiiwwan Baramaa',
    'faq.help': 'Gargaarsa Ariifachiisaa',
    'faq.help.desc': 'Gargaarsa battaalaa barbaadduu? Gareen gargaarsa keenya maddee garaa garaa irratti si\'aayoodha.',
    'faq.seeMore': 'Gaaffiiwwan Dabalataa Ilaali',
    'faq.seeLess': 'Xiqqaatti Ilaali',
    'courses.explore.title': 'Koorsiiwwan Ilaalaa',
    'courses.explore.desc': 'Tarree koorsiiwwan keenyaa ballaa ta\'e ilaalaa. Yaadannoo, gaaffii shaakalaa fi viidiyoo isiniif dhiyeessina.',
    'courses.entrance.title': 'Koorsiiwwan Qophii Seensaa',
    'courses.entrance.desc': 'Qormaata seensaa yunivarsiitii keessaniif koorsiiwwan keenya ittiin qophaa\'aa.',
    'courses.search.placeholder': 'Barumsa barbaadi...',
    'courses.natural': 'Saayinsii Uumamaa',
    'courses.social': 'Saayinsii Hawwaasaa',
    'courses.noResults': 'Koorsiin walsimu hin argamne',
    'footer.desc': 'Madii barnootaa qofa miti, nuy hawaasa milkaa\'inaati. Yaadannoo ogeessotaa fi gorsa barattoota angafaa walitti fiduun barattoota Itoophiyaa ni jajjabeessina.',
    'footer.platform': 'Tarbaaya',
    'footer.legal': 'Seera',
    'footer.dataSaver': 'Data Saver',
    'footer.enabled': 'Banameera',
    'footer.disabled': 'Cufameera',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('tilla_lang');
    return (saved as Language) || 'EN';
  });

  useEffect(() => {
    localStorage.setItem('tilla_lang', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
