# Generated by Django 4.2.30 on 2026-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_enrollment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='progress',
            new_name='courses_pro_user_id_aa1c08_idx',
            old_name='courses_pro_user_course_idx',
        ),
        migrations.RenameIndex(
            model_name='progress',
            new_name='courses_pro_updated_db8d5d_idx',
            old_name='courses_pro_updated_idx',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Free preview lessons are visible without a payment.'),
        ),
    ]
