# Generated by Django 4.2.30 on 2026-06-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_courses_pro_user_course_idx_courses_pro_user_id_aa1c08_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catalogue_code',
            field=models.CharField(blank=True, db_index=True, help_text="Frontend course code from courseCatalogue.ts (e.g. 'FLEn-1011'). Used to bridge cart → backend PK. Set this in the admin for every published course.", max_length=50),
        ),
    ]
